name: Automated Tests

on:
  pull_request:
    branches: ["*"]
    types: [opened, synchronize, reopened]
  push:
    branches: ["main", "dev/main"]

# Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node 20
        uses: actions/setup-node@v3
        with:
          node-version: 20
          
      - uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install deps (with cache)
        run: yarn install
        
      - name: Build
        run: yarn build

      - name: Test with coverage
        run: yarn testc
        
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}